### PR TITLE
Some refactoring to allow code reuse for the next parts of this example

### PR DESCRIPTION
**Pull request by drpdr**
1. Removed `employee.c` and moved its content plus `set_read_only()` to
`employee.h;
2. updated `Makefile` to reflect the changes.

### CODE REVIEW

**Comment by drpdr** [comment]
PR ready for review (6956bd8).

**Comment by ltratt** [comment]
What is https://github.com/drpdr/cheri-examples/commit/6956bd8e3baeae89ec9aed8de0a9fd70098968e8? Do you want to squash before review?

**Comment by drpdr** [comment]
> What is [drpdr@6956bd8](https://github.com/drpdr/cheri-examples/commit/6956bd8e3baeae89ec9aed8de0a9fd70098968e8)? Do you want to squash before review?

Do you want me to squash before review? I had forgotten `employee.h` when I opened the PR, sorry.

**Comment by ltratt** [comment]
You don't have to squash, but commits at least need sensible messages otherwise the reviewer can't know what's going on. Please squash or reword as you see fit and force push.

**Comment by drpdr** [comment]
> You don't have to squash, but commits at least need sensible messages otherwise the reviewer can't know what's going on. Please squash or reword as you see fit and force push.

OK.

**Comment by drpdr** [comment]
PR Ready for review. Force pushed with meaningful commit message as requested.

**Pull request merged**
