### PR TITLE
Add examples for checking boundaries (mask, lenght).

### PR DESCRIPTION
**Pull request by alex4o**
Small, examples that can be useful to showcase how the mask and the length checking works for various values.

### CODE REVIEW

**Comment by ltratt** [comment]
Have these been formatted using the in-repo format settings thingy?

**Comment by alex4o** [comment]
Oh I forgot, fixed it now.

**Comment by ltratt** [comment]
Please squash.

**Comment by alex4o** [comment]
Done

**Comment by ltratt** [comment]
I've just realised (and should have noticed earlier -- sorry!), there's no documentation for this example. Can we add a quick doc comment to the top of the `.c` file making clear what the example is intended to show?

**Comment by alex4o** [comment]
I think this should be sufficient.

**Comment by ltratt** [comment]
Please squash (and you probably want to fix the typo in the first commit :) ).

**Comment by alex4o** [comment]
Done

**Comment by alex4o** [comment]
Do you want to try again, as buildbot should work today.

**Comment by alex4o** [comment]
@ltratt Sry to bother you, but can you try running bors again? The problem last time wasn't with the code, it was with buildbot.

**Comment by alex4o** [comment]
bors try

**Comment by alex4o** [comment]
bors try

**Comment by alex4o** [comment]
I don't know why but it wasn't building with buildbot, but it was building fine locally. So I changed the headers, and that helped.

**Comment by ltratt** [comment]
Please squash.

**Comment by alex4o** [comment]
Done

**Pull request merged**
