### PR TITLE
We don't need CMake 3.15.0.

### PR DESCRIPTION
**Pull request by ltratt**
Since Debian 10 only has 3.13.0 this requirement is a bit annoying!

### CODE REVIEW

**Comment by drpdr** [comment]
bors try

**Comment by drpdr** [comment]
bors try

**Comment by ltratt** [comment]
We'll need to rebase this against master *after* #26 has been merged, in order for this to stand a chance of being merged.

**Comment by drpdr** [comment]
The only problem now is the formatting of `instructions.h`, otherwise this can be merged without waiting for #26.

**Comment by drpdr** [comment]
> We'll need to rebase this against master _after_ #26 has been merged, in order for this to stand a chance of being merged.

If I am not mistaken, you forked after #25, right? We did not have the tests at that time so this should work without waiting for #26.

**Comment by ltratt** [comment]
Until we've got buildbot working again (in #26 or wherever), there's no point trying to merge other open PRs. Let's just wait. Rebasing against master will be trivial for this PR.

**Comment by drpdr** [comment]
> Until we've got buildbot working again (in #26 or wherever), there's no point trying to merge other open PRs. Let's just wait. Rebasing against master will be trivial for this PR.

OK, before stopping the containers I wanted to try. Since `buildbot` should work without the tests now. And here `.buildbot.sh` doesn't run tests. That's why I tried.

**Comment by ltratt** [comment]
OK for me to rebase against master?

**Comment by drpdr** [comment]
> OK for me to rebase against master?

Yes, please. So, you get rid of the formatting problem in `instructions.h`.

**Comment by ltratt** [comment]
> So, you get rid of the formatting problem in instructions.h

Huh?

**Comment by drpdr** [comment]
> > So, you get rid of the formatting problem in instructions.h
> 
> Huh?

I've "re-fixed" it but that file is "unstable". It actually should have passed the previous builds. It is weird.

**Comment by ltratt** [comment]
I feel like I'm missing something: this PR changes one line in a CMake file. What's a C header got to do with that?

**Comment by drpdr** [comment]
> I feel like I'm missing something: this PR changes one line in a CMake file. What's a C header got to do with that?

As I said, this build now should fail because of the header file. It is not your fault but you "inherited" the issue. I always run `clang-format` but in some previous merges something must have been missed. Anyway, feel free to rebase and everything should be OK.

**Comment by ltratt** [comment]
OK, I'm baffled because if there's a problem on master, #26 couldn't have merged.

Anyway, I've force pushed.

**Comment by drpdr** [comment]
bors ping

**Comment by drpdr** [comment]
bors try

**Comment by drpdr** [comment]
bors cancel

**Pull request merged**
