### PR TITLE
Try to fix the linker issue

### PR DESCRIPTION
**Pull request by drpdr**
Draft PR to check whether the linker issue has been solved.

### CODE REVIEW

**Comment by drpdr** [comment]
bors try

**Comment by drpdr** [comment]
PR ready for review in 824529c.

**Comment by ltratt** [comment]
Please squash.

**Comment by drpdr** [comment]
Squashed.

**Comment by ltratt** [comment]
Can we change the commit message? Because we're not exactly fixing a linker issue: we're making sure we use the system `ld` right?

**Comment by drpdr** [comment]
> Can we change the commit message? Because we're not exactly fixing a linker issue: we're making sure we use the system `ld` right?

Can I just amend it?

**Comment by ltratt** [comment]
Please force push an update.

**Comment by drpdr** [comment]
> Please force push an update.

Done.

**Pull request merged**
