### PR TITLE
Add CI config.

### PR DESCRIPTION
**Pull request by alex4o**
Test the Buildbod and bors configs.

### CODE REVIEW

**Comment by alex4o** [comment]
bors try

**Comment by alex4o** [comment]
bors try

**Comment by alex4o** [comment]
bors try

**Comment by ltratt** [comment]
@alex4o I guess this is more-or-less ready for merging? If so, can you get the status update working or, perhaps, we should disable it? Or maybe it doesn't need it. And generally for commit messages, we prefer simple verbs so the main commit title would be "Add CI config." And you might want to add a spell checker to your commit message editor ;)

**Comment by alex4o** [comment]
What do you mean, by the status update, It is working already I think?

**Comment by ltratt** [comment]
I should also have asked: let's use 4 spaces for the shell script please. Sorry :) Feel free to do that as a force push and then I'll try a merge after that.

**Comment by alex4o** [comment]
I think this is ready to merge.

**Comment by ltratt** [comment]
I don't understand this bors error. Does anyone have any suggestions?

**Pull request merged**
